# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField()),
                ('num_requests', models.IntegerField()),
                ('last_request', models.DateTimeField()),
                ('search1', models.TextField(blank=True, null=True)),
                ('search2', models.TextField(blank=True, null=True)),
                ('search3', models.TextField(blank=True, null=True)),
                ('search1_date', models.DateTimeField(blank=True, null=True)),
                ('search2_date', models.DateTimeField(blank=True, null=True)),
                ('search3_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(unique=True)),
                ('last_search', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordsContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Contacts')),
                ('keywordid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.SmallIntegerField(choices=[(1, 'CrossRef'), (2, 'JournalTOCs'), (3, 'arXiv')])),
                ('medium', models.SmallIntegerField(choices=[(1, 'Article'), (2, 'Book'), (3, 'Dissertation')])),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('url', models.TextField()),
                ('doi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultsContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Contacts')),
                ('resultid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Results')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywordid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Keywords')),
                ('resultid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Results')),
            ],
        ),
    ]
